doctrine:
    dbal:
        #        url: '%env(resolve:DATABASE_URL)%'

        dbname:          '%env(resolve:DATABASE_NAME)%'
        host:            '%env(resolve:DATABASE_HOST)%'
        port:            '%env(resolve:DATABASE_PORT)%'
        user:            '%env(resolve:DATABASE_USER)%'
        password:        '%env(resolve:DATABASE_PASSWORD)%'
        driver:          '%env(resolve:DATABASE_DRIVER)%'
        server_version:  '%env(resolve:DATABASE_SERVER_VERSION)%'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            fruit_id: App\Market\Infrastructure\Persistence\Doctrine\FruitIdType
            vegetable_id: App\Market\Infrastructure\Persistence\Doctrine\VegetableIdType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Market/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Market\Domain'
                alias: App
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
